[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ft_package"
home-page = "https://github.com/yuran653/42_python_for_ds/tree/main/python00/ex09"
author = "jgoldste"
author-email = "jgoldste@student.42bangkok.com"
license = "MIT"
